FROM ganers/centos-7-systemd
RUN yum install wget -y
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-x86_64.rpm
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-x86_64.rpm.sha512
RUN shasum -a 512 -c elasticsearch-7.15.2-x86_64.rpm.sha512
RUN rpm --install elasticsearch-7.15.2-x86_64.rpm

#RUN yum -y install httpd; yum clean all; systemctl enable httpd.service

EXPOSE 9200
EXPOSE 9300

RUN /bin/systemctl daemon-reload
RUN /bin/systemctl enable elasticsearch.service

#CMD ["/usr/sbin/init"]
