FROM ganers/centos-7-systemd
RUN yum install wget -y
RUN yum install perl-Digest-SHA-5.85-4.el7.x86_64.rpm -y
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-x86_64.rpm
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-x86_64.rpm.sha512
RUN shasum -a 512 -c elasticsearch-7.15.2-x86_64.rpm.sha512
RUN rpm --install elasticsearch-7.15.2-x86_64.rpm

EXPOSE 9200
EXPOSE 9300

RUN /bin/systemctl daemon-reload
RUN /bin/systemctl enable elasticsearch.service

#CMD ["/usr/sbin/init"]
